name = "agile-gestao-landing"
compatibility_date = "2024-09-02"

[build]
command = "npm run build"
cwd = "."

[build.upload]
format = "directory"
dir = "out"

[[routes]]
pattern = "*"
custom_domain = true

[env.production]
name = "agile-gestao-landing"

[env.production.vars]
NODE_ENV = "production"